### PR TITLE
Some additions

### PR DESCRIPTION
**Pull request by Super-Baleine**
Hey,
Firstly, i think the user have to make the choice if the script have to get the server IP or not.
And i added a loop.
:whale:

### CODE REVIEW

**Comment by angristan** [comment]
Thanks for the loop, but there is no point to ask the user if he accepts that the script will get the server IP. The script will not work without the IP.

**Comment by Super-Baleine** [comment]
of course yes, check at the beginning

**Comment by angristan** [comment]
It makes no sense ^^' Why would anyone want that ?

**Comment by Super-Baleine** [comment]
About the read to know if the user allows the script to get IP ?
Because privacy... There are logs on the server which we use to get the public IP...

**Comment by Super-Baleine** [comment]
But the user knows that if he refuses, he will not be able to manage OpenVPN, so, this is just an ethical enhancement.

what do you think about ?

**Comment by angristan** [comment]
The public IP is, by definition, public, if you want to make a VPN server, you know that you will use the server IP, so it's not private, it's obvious... It's not related to privacy here, but only that you don't know what you're doing \o/

Can you please open another PR with the loop only ? :smiley:

**Comment by Super-Baleine** [comment]
Maybe the user don't want give its public IP to the server which we use to get this public IP ? I think it's related to privacy x)

Okay, if u want x)

**Comment by angristan** [comment]
The script gets the server's public IP, not the user's one

**Comment by Super-Baleine** [comment]
But, you know, me, like many other people, i think, don't want to give our public ip to a random server.
You understand my point of view or... ? x)

**Comment by angristan** [comment]
You are using this script on your server, not a "random" one, wtf

**Comment by Super-Baleine** [comment]
No, it's not what i mean... Doesn't matter XD

**Comment by angristan** [comment]
**you** run a script that **you** know on **your** server, what is the problem ?

**Comment by Super-Baleine** [comment]
No, i mean that the script take your ip from an another server.
But, maybe the user don't wanna give its public ip to this server.
maybe the user will just use its VPN just to access to its LAN when he's at work.

It's just a very small thing x)

**Comment by Super-Baleine** [comment]
here : 
`IP=$(wget -qO- ipv4.icanhazip.com)`

**Pull request closed without merging**
