### PR TITLE
Add mlock and iOS8.4/Android 4.4.2+ support

### PR DESCRIPTION
**Pull request by Harvester57**

### CODE REVIEW

**Comment by angristan** [comment]
Android supports AES GCM ^^ (cf your link)

**Comment by Harvester57** [comment]
Android 4.4.2 supports AES-256-GCM and AES-128-GCM, that's true, but it's not true for more recents releases. Android 5.0+ only support AES-128-GCM (see here for reasons : https://community.qualys.com/message/28012#28012), which is not usable with your slow profile. 

As the slow profile only uses 256 bits ciphers, DHE-AES-256-CBC is the strongest one with PFS (see https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=5.0.0 for Android 5.0.0). Or you could use AES-128-GCM for your slow profile ass a fallback, to support both 4.4.4 (with 256-GCM cipher) and 5.0.0+ (with 128-GCM cipher). Your call :)

**Comment by Harvester57** [comment]
To support the latter option, here's a chromium developper statement (https://bugs.chromium.org/p/chromium/issues/detail?id=442572#c9) : 

> To recap the logic here:
> On a scale of security AND speed
> 128-GCM > 128-CBC
> 128-GCM > 256-CBC
> 128-GCM ~ 256-GCM (again, we are counting both performance and effective security here)

However, a number of servers are poorly configured, where the administrator has configured the server to believe that 256 bit ciphers in any block mode are always better than 128-bit.

This is wrong. **128-GCM is far, far more desirable than 256-CBC**. Hence why 256-CBC should be disabled.

This bug is not about 256-GCM. Supporting that is a non-goal at this time. It is likely that a bug to support it will go WontFixed at this time.

So maybe I should change the slow profile fallback to AES-128-GCM. What do you think ?

**Comment by angristan** [comment]
> Android 4.4.2 supports AES-256-GCM and AES-128-GCM, that's true, but it's not true for more recents releases. Android 5.0+ only support AES-128-GCM (see here for reasons : https://community.qualys.com/message/28012#28012), which is not usable with your slow profile.

That's **very** strange because my Android is running 5.1 and works well with `tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384`...

> As the slow profile only uses 256 bits ciphers, DHE-AES-256-CBC is the strongest one with PFS (see https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=5.0.0 for Android 5.0.0). Or you could use AES-128-GCM for your slow profile ass a fallback, to support both 4.4.4 (with 256-GCM cipher) and 5.0.0+ (with 128-GCM cipher). Your call :)

Yep AES-128GCM is the best cipher anyway

**Comment by angristan** [comment]
AES  256 is more vulnerable to timing attacks so : 

> AES-128-GCM > AES-256-GCM > AES-128-CBC > AES-256-CBC

So maybe on both profiles we should only put `TLS-DHE-RSA-WITH-AES-128-GCM-SHA256` ^^

**Pull request closed without merging**
